heat_template_version: 2017-02-24
description: Just a simple template for creating a router that is using the external network as gateway and has an internal network on a interface

parameters:
  private_network_name:
    type: string
    description: The name of the private network
    default: private_net

  private_subnet_name:
    type: string
    description: The name of the private subnet
    default: private_subnet

  external_network_name:
    type: string
    description: The name of the external network
    default: external

  router_name:
    type: string
    description: The name of the router
    default: router1

resources:
  private_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_network_name }

  private_network_sub:
    type: OS::Neutron::Subnet
    properties:
      name : { get_param: private_subnet_name }
      network_id: { get_resource: private_network }
      cidr: 192.168.10.0/24
      gateway_ip: 192.168.10.1

  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: router_name }
      external_gateway_info:
        network: { get_param: external_network_name }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_network_sub }
