heat_template_version: 2017-02-24
description: Deployment of 2 default servers

parameters:
  instance_count:
    type: number
    description: Total of instances to spawn
    default: 2
    constraints:
      - range: { min: 1, max: 5 }

resources:
  instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_count } 
      resource_def:
        type: OS::Nova::Server
        properties:
          flavor: m1.tiny
          image: cirros
          name: test-%index%
