heat_template_version: 2017-02-24
description: Just a template to setup a security group, this just allows all ICMP, and HTTP ingress, ethernet type IPv4 (default) and IPv6. direction default is ingress, just put it in there to show it.

resources:

  security_rules:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Create a security group with some extra rules
      name: Custom rules
      rules:
        - protocol: icmp 
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
          direction: ingress
        - protocol: tcp
          ethertype: IPv6
          remote_ip_prefix: ::/0
          port_range_min: 80
          port_range_max: 80
          direction: ingress
