heat_template_version: 2017-02-24
description: Create an instance with a cinder volume attached


resources:
  instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny

  volume:
    type: OS::Cinder::Volume
    properties:
      size: 1

  volume_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: instance }

